# Generated by Django 4.1.1 on 2022-09-22 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_module', '0002_remove_cart_is_paid_cart_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
