# Generated by Django 4.1.1 on 2022-09-24 17:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard_module', '0004_discount_codes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Discount_codes',
            new_name='Discountcodes',
        ),
    ]
