# Generated by Django 4.1.1 on 2022-09-25 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_module', '0010_alter_cart_country_alter_cart_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='amount_paid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
