# Generated by Django 4.1.1 on 2022-09-26 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_module', '0011_cart_amount_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdiscountcode',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
