# Generated by Django 4.1.1 on 2022-09-26 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_module', '0012_userdiscountcode_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdiscountcode',
            name='cart',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard_module.cart'),
        ),
    ]
