# Generated by Django 4.1.1 on 2022-09-26 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_module', '0013_userdiscountcode_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdiscountcode',
            name='user',
        ),
    ]
