# Generated by Django 4.1.1 on 2022-09-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_module', '0015_cart_independent_amount_cart_transection_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='transection_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
