# Generated by Django 4.1.1 on 2022-09-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_module', '0017_alter_cart_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='payment_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
