# Generated by Django 4.1.1 on 2022-09-28 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_module', '0018_alter_cart_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
