# Generated by Django 4.1.1 on 2022-10-05 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_module', '0013_comments'),
        ('dashboard_module', '0019_userinfo_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_module.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_module.userinfo')),
            ],
        ),
    ]
