# Generated by Django 4.1.1 on 2022-09-18 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_module', '0003_category_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='store_module.category'),
        ),
    ]
