# Generated by Django 4.1.1 on 2022-09-18 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_module', '0005_remove_product_bestseller_remove_product_new_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.CharField(choices=[('Trending', 'Trending'), ('NEW', 'New'), ('Bestseller', 'Bestseller')], max_length=200),
        ),
    ]
