# Generated by Django 4.1.1 on 2022-09-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_module', '0006_alter_product_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='original_price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
