# Generated by Django 4.1.1 on 2022-09-19 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_module', '0007_alter_product_original_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.CharField(blank=True, choices=[('Trending', 'Trending'), ('NEW', 'New'), ('Bestseller', 'Bestseller')], max_length=200, null=True),
        ),
    ]
