# Generated by Django 4.1.1 on 2022-09-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_module', '0009_productimagegallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additional_information',
            field=models.TextField(blank=True, null=True),
        ),
    ]
